[package]
name = "mfproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13"
chrono = "0.4"
native-tls = "0.2"
reqwest = { version = "0.11", features = [ "blocking", "json" ] }
serde = { version = "1.0", features = [ "derive" ] }
tiny_http = "0.9"
url = "2.2"
